package com.internation.info.model;

import java.io.Serializable;
import java.util.Date;

public class Answer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.id
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.uId
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    private Integer uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.content
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.floor
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    private Integer floor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.answerTime
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    private Date answerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.isAdopt
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    private Integer isAdopt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.requestId
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    private Integer requestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table answer
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.id
     *
     * @return the value of answer.id
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.id
     *
     * @param id the value for answer.id
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.uId
     *
     * @return the value of answer.uId
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.uId
     *
     * @param uId the value for answer.uId
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.content
     *
     * @return the value of answer.content
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.content
     *
     * @param content the value for answer.content
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.floor
     *
     * @return the value of answer.floor
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public Integer getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.floor
     *
     * @param floor the value for answer.floor
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.answerTime
     *
     * @return the value of answer.answerTime
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public Date getAnswerTime() {
        return answerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.answerTime
     *
     * @param answerTime the value for answer.answerTime
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public void setAnswerTime(Date answerTime) {
        this.answerTime = answerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.isAdopt
     *
     * @return the value of answer.isAdopt
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public Integer getIsAdopt() {
        return isAdopt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.isAdopt
     *
     * @param isAdopt the value for answer.isAdopt
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public void setIsAdopt(Integer isAdopt) {
        this.isAdopt = isAdopt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.requestId
     *
     * @return the value of answer.requestId
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public Integer getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.requestId
     *
     * @param requestId the value for answer.requestId
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public void setRequestId(Integer requestId) {
        this.requestId = requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uId=").append(uId);
        sb.append(", content=").append(content);
        sb.append(", floor=").append(floor);
        sb.append(", answerTime=").append(answerTime);
        sb.append(", isAdopt=").append(isAdopt);
        sb.append(", requestId=").append(requestId);
        sb.append("]");
        return sb.toString();
    }
}