package com.internation.info.model;

import java.io.Serializable;
import java.util.Date;

import org.springframework.stereotype.Repository;
@Repository
public class BasicMessageWall implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basicmessagewall.id
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basicmessagewall.userId
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basicmessagewall.userName
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basicmessagewall.content
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basicmessagewall.createTime
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basicmessagewall.updateTime
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table basicmessagewall
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basicmessagewall.id
     *
     * @return the value of basicmessagewall.id
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basicmessagewall.id
     *
     * @param id the value for basicmessagewall.id
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basicmessagewall.userId
     *
     * @return the value of basicmessagewall.userId
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basicmessagewall.userId
     *
     * @param userId the value for basicmessagewall.userId
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basicmessagewall.userName
     *
     * @return the value of basicmessagewall.userName
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basicmessagewall.userName
     *
     * @param userName the value for basicmessagewall.userName
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basicmessagewall.content
     *
     * @return the value of basicmessagewall.content
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basicmessagewall.content
     *
     * @param content the value for basicmessagewall.content
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basicmessagewall.createTime
     *
     * @return the value of basicmessagewall.createTime
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basicmessagewall.createTime
     *
     * @param createTime the value for basicmessagewall.createTime
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basicmessagewall.updateTime
     *
     * @return the value of basicmessagewall.updateTime
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basicmessagewall.updateTime
     *
     * @param updateTime the value for basicmessagewall.updateTime
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicmessagewall
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", content=").append(content);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}