package com.internation.info.model;

import java.io.Serializable;
import java.util.Date;

import org.springframework.stereotype.Repository;
@Repository
public class FileDownload implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filedownload.id
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filedownload.fileId
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filedownload.fileName
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filedownload.uId
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    private Integer uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filedownload.downLoadTime
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    private Date downLoadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table filedownload
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filedownload.id
     *
     * @return the value of filedownload.id
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filedownload.id
     *
     * @param id the value for filedownload.id
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filedownload.fileId
     *
     * @return the value of filedownload.fileId
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filedownload.fileId
     *
     * @param fileId the value for filedownload.fileId
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filedownload.fileName
     *
     * @return the value of filedownload.fileName
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filedownload.fileName
     *
     * @param fileName the value for filedownload.fileName
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filedownload.uId
     *
     * @return the value of filedownload.uId
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filedownload.uId
     *
     * @param uId the value for filedownload.uId
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filedownload.downLoadTime
     *
     * @return the value of filedownload.downLoadTime
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    public Date getDownLoadTime() {
        return downLoadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filedownload.downLoadTime
     *
     * @param downLoadTime the value for filedownload.downLoadTime
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    public void setDownLoadTime(Date downLoadTime) {
        this.downLoadTime = downLoadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedownload
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fileId=").append(fileId);
        sb.append(", fileName=").append(fileName);
        sb.append(", uId=").append(uId);
        sb.append(", downLoadTime=").append(downLoadTime);
        sb.append("]");
        return sb.toString();
    }
}