package com.internation.info.model;

import java.io.Serializable;
import java.util.Date;

import org.springframework.stereotype.Repository;
@Repository
public class GroupMember implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupmember.id
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupmember.groupId
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupmember.member
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    private String member;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupmember.createdTime
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupmember.status
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupmember.nickName
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupmember.avatar
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupmember.sign
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table groupmember
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupmember.id
     *
     * @return the value of groupmember.id
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupmember.id
     *
     * @param id the value for groupmember.id
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupmember.groupId
     *
     * @return the value of groupmember.groupId
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupmember.groupId
     *
     * @param groupId the value for groupmember.groupId
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupmember.member
     *
     * @return the value of groupmember.member
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    public String getMember() {
        return member;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupmember.member
     *
     * @param member the value for groupmember.member
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    public void setMember(String member) {
        this.member = member;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupmember.createdTime
     *
     * @return the value of groupmember.createdTime
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupmember.createdTime
     *
     * @param createdTime the value for groupmember.createdTime
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupmember.status
     *
     * @return the value of groupmember.status
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupmember.status
     *
     * @param status the value for groupmember.status
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupmember.nickName
     *
     * @return the value of groupmember.nickName
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupmember.nickName
     *
     * @param nickName the value for groupmember.nickName
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupmember.avatar
     *
     * @return the value of groupmember.avatar
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupmember.avatar
     *
     * @param avatar the value for groupmember.avatar
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupmember.sign
     *
     * @return the value of groupmember.sign
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupmember.sign
     *
     * @param sign the value for groupmember.sign
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    public void setSign(String sign) {
        this.sign = sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmember
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", groupId=").append(groupId);
        sb.append(", member=").append(member);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", status=").append(status);
        sb.append(", nickName=").append(nickName);
        sb.append(", avatar=").append(avatar);
        sb.append(", sign=").append(sign);
        sb.append("]");
        return sb.toString();
    }
}