package com.internation.info.model;

import java.io.Serializable;
import java.util.Date;

import org.springframework.stereotype.Repository;
@Repository
public class OtherInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherinfo.id
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherinfo.title
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherinfo.createTime
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherinfo.username
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherinfo.url
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherinfo.seecount
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    private String seecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherinfo.infoType
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    private String infoType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherinfo.source
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherinfo.pictureUrl
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    private String pictureUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherinfo.content
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    private byte[] content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table otherinfo
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherinfo.id
     *
     * @return the value of otherinfo.id
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherinfo.id
     *
     * @param id the value for otherinfo.id
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherinfo.title
     *
     * @return the value of otherinfo.title
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherinfo.title
     *
     * @param title the value for otherinfo.title
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherinfo.createTime
     *
     * @return the value of otherinfo.createTime
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherinfo.createTime
     *
     * @param createTime the value for otherinfo.createTime
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherinfo.username
     *
     * @return the value of otherinfo.username
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherinfo.username
     *
     * @param username the value for otherinfo.username
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherinfo.url
     *
     * @return the value of otherinfo.url
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherinfo.url
     *
     * @param url the value for otherinfo.url
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherinfo.seecount
     *
     * @return the value of otherinfo.seecount
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    public String getSeecount() {
        return seecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherinfo.seecount
     *
     * @param seecount the value for otherinfo.seecount
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    public void setSeecount(String seecount) {
        this.seecount = seecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherinfo.infoType
     *
     * @return the value of otherinfo.infoType
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    public String getInfoType() {
        return infoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherinfo.infoType
     *
     * @param infoType the value for otherinfo.infoType
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    public void setInfoType(String infoType) {
        this.infoType = infoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherinfo.source
     *
     * @return the value of otherinfo.source
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherinfo.source
     *
     * @param source the value for otherinfo.source
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherinfo.pictureUrl
     *
     * @return the value of otherinfo.pictureUrl
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherinfo.pictureUrl
     *
     * @param pictureUrl the value for otherinfo.pictureUrl
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherinfo.content
     *
     * @return the value of otherinfo.content
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    public byte[] getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherinfo.content
     *
     * @param content the value for otherinfo.content
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    public void setContent(byte[] content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table otherinfo
     *
     * @mbggenerated Sat May 05 23:56:21 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", createTime=").append(createTime);
        sb.append(", username=").append(username);
        sb.append(", url=").append(url);
        sb.append(", seecount=").append(seecount);
        sb.append(", infoType=").append(infoType);
        sb.append(", source=").append(source);
        sb.append(", pictureUrl=").append(pictureUrl);
        sb.append(", content=").append(content);
        sb.append("]");
        return sb.toString();
    }
}