package com.internation.info.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.springframework.stereotype.Repository;
@Repository
public class QuestionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public QuestionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table question
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andQuestionerIsNull() {
            addCriterion("questioner is null");
            return (Criteria) this;
        }

        public Criteria andQuestionerIsNotNull() {
            addCriterion("questioner is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionerEqualTo(String value) {
            addCriterion("questioner =", value, "questioner");
            return (Criteria) this;
        }

        public Criteria andQuestionerNotEqualTo(String value) {
            addCriterion("questioner <>", value, "questioner");
            return (Criteria) this;
        }

        public Criteria andQuestionerGreaterThan(String value) {
            addCriterion("questioner >", value, "questioner");
            return (Criteria) this;
        }

        public Criteria andQuestionerGreaterThanOrEqualTo(String value) {
            addCriterion("questioner >=", value, "questioner");
            return (Criteria) this;
        }

        public Criteria andQuestionerLessThan(String value) {
            addCriterion("questioner <", value, "questioner");
            return (Criteria) this;
        }

        public Criteria andQuestionerLessThanOrEqualTo(String value) {
            addCriterion("questioner <=", value, "questioner");
            return (Criteria) this;
        }

        public Criteria andQuestionerLike(String value) {
            addCriterion("questioner like", value, "questioner");
            return (Criteria) this;
        }

        public Criteria andQuestionerNotLike(String value) {
            addCriterion("questioner not like", value, "questioner");
            return (Criteria) this;
        }

        public Criteria andQuestionerIn(List<String> values) {
            addCriterion("questioner in", values, "questioner");
            return (Criteria) this;
        }

        public Criteria andQuestionerNotIn(List<String> values) {
            addCriterion("questioner not in", values, "questioner");
            return (Criteria) this;
        }

        public Criteria andQuestionerBetween(String value1, String value2) {
            addCriterion("questioner between", value1, value2, "questioner");
            return (Criteria) this;
        }

        public Criteria andQuestionerNotBetween(String value1, String value2) {
            addCriterion("questioner not between", value1, value2, "questioner");
            return (Criteria) this;
        }

        public Criteria andQuestionTimeIsNull() {
            addCriterion("questionTime is null");
            return (Criteria) this;
        }

        public Criteria andQuestionTimeIsNotNull() {
            addCriterion("questionTime is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionTimeEqualTo(Date value) {
            addCriterion("questionTime =", value, "questionTime");
            return (Criteria) this;
        }

        public Criteria andQuestionTimeNotEqualTo(Date value) {
            addCriterion("questionTime <>", value, "questionTime");
            return (Criteria) this;
        }

        public Criteria andQuestionTimeGreaterThan(Date value) {
            addCriterion("questionTime >", value, "questionTime");
            return (Criteria) this;
        }

        public Criteria andQuestionTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("questionTime >=", value, "questionTime");
            return (Criteria) this;
        }

        public Criteria andQuestionTimeLessThan(Date value) {
            addCriterion("questionTime <", value, "questionTime");
            return (Criteria) this;
        }

        public Criteria andQuestionTimeLessThanOrEqualTo(Date value) {
            addCriterion("questionTime <=", value, "questionTime");
            return (Criteria) this;
        }

        public Criteria andQuestionTimeIn(List<Date> values) {
            addCriterion("questionTime in", values, "questionTime");
            return (Criteria) this;
        }

        public Criteria andQuestionTimeNotIn(List<Date> values) {
            addCriterion("questionTime not in", values, "questionTime");
            return (Criteria) this;
        }

        public Criteria andQuestionTimeBetween(Date value1, Date value2) {
            addCriterion("questionTime between", value1, value2, "questionTime");
            return (Criteria) this;
        }

        public Criteria andQuestionTimeNotBetween(Date value1, Date value2) {
            addCriterion("questionTime not between", value1, value2, "questionTime");
            return (Criteria) this;
        }

        public Criteria andIsresolveIsNull() {
            addCriterion("isresolve is null");
            return (Criteria) this;
        }

        public Criteria andIsresolveIsNotNull() {
            addCriterion("isresolve is not null");
            return (Criteria) this;
        }

        public Criteria andIsresolveEqualTo(Integer value) {
            addCriterion("isresolve =", value, "isresolve");
            return (Criteria) this;
        }

        public Criteria andIsresolveNotEqualTo(Integer value) {
            addCriterion("isresolve <>", value, "isresolve");
            return (Criteria) this;
        }

        public Criteria andIsresolveGreaterThan(Integer value) {
            addCriterion("isresolve >", value, "isresolve");
            return (Criteria) this;
        }

        public Criteria andIsresolveGreaterThanOrEqualTo(Integer value) {
            addCriterion("isresolve >=", value, "isresolve");
            return (Criteria) this;
        }

        public Criteria andIsresolveLessThan(Integer value) {
            addCriterion("isresolve <", value, "isresolve");
            return (Criteria) this;
        }

        public Criteria andIsresolveLessThanOrEqualTo(Integer value) {
            addCriterion("isresolve <=", value, "isresolve");
            return (Criteria) this;
        }

        public Criteria andIsresolveIn(List<Integer> values) {
            addCriterion("isresolve in", values, "isresolve");
            return (Criteria) this;
        }

        public Criteria andIsresolveNotIn(List<Integer> values) {
            addCriterion("isresolve not in", values, "isresolve");
            return (Criteria) this;
        }

        public Criteria andIsresolveBetween(Integer value1, Integer value2) {
            addCriterion("isresolve between", value1, value2, "isresolve");
            return (Criteria) this;
        }

        public Criteria andIsresolveNotBetween(Integer value1, Integer value2) {
            addCriterion("isresolve not between", value1, value2, "isresolve");
            return (Criteria) this;
        }

        public Criteria andAdoptTheContentIsNull() {
            addCriterion("adoptTheContent is null");
            return (Criteria) this;
        }

        public Criteria andAdoptTheContentIsNotNull() {
            addCriterion("adoptTheContent is not null");
            return (Criteria) this;
        }

        public Criteria andAdoptTheContentEqualTo(String value) {
            addCriterion("adoptTheContent =", value, "adoptTheContent");
            return (Criteria) this;
        }

        public Criteria andAdoptTheContentNotEqualTo(String value) {
            addCriterion("adoptTheContent <>", value, "adoptTheContent");
            return (Criteria) this;
        }

        public Criteria andAdoptTheContentGreaterThan(String value) {
            addCriterion("adoptTheContent >", value, "adoptTheContent");
            return (Criteria) this;
        }

        public Criteria andAdoptTheContentGreaterThanOrEqualTo(String value) {
            addCriterion("adoptTheContent >=", value, "adoptTheContent");
            return (Criteria) this;
        }

        public Criteria andAdoptTheContentLessThan(String value) {
            addCriterion("adoptTheContent <", value, "adoptTheContent");
            return (Criteria) this;
        }

        public Criteria andAdoptTheContentLessThanOrEqualTo(String value) {
            addCriterion("adoptTheContent <=", value, "adoptTheContent");
            return (Criteria) this;
        }

        public Criteria andAdoptTheContentLike(String value) {
            addCriterion("adoptTheContent like", value, "adoptTheContent");
            return (Criteria) this;
        }

        public Criteria andAdoptTheContentNotLike(String value) {
            addCriterion("adoptTheContent not like", value, "adoptTheContent");
            return (Criteria) this;
        }

        public Criteria andAdoptTheContentIn(List<String> values) {
            addCriterion("adoptTheContent in", values, "adoptTheContent");
            return (Criteria) this;
        }

        public Criteria andAdoptTheContentNotIn(List<String> values) {
            addCriterion("adoptTheContent not in", values, "adoptTheContent");
            return (Criteria) this;
        }

        public Criteria andAdoptTheContentBetween(String value1, String value2) {
            addCriterion("adoptTheContent between", value1, value2, "adoptTheContent");
            return (Criteria) this;
        }

        public Criteria andAdoptTheContentNotBetween(String value1, String value2) {
            addCriterion("adoptTheContent not between", value1, value2, "adoptTheContent");
            return (Criteria) this;
        }

        public Criteria andSeeCountIsNull() {
            addCriterion("seeCount is null");
            return (Criteria) this;
        }

        public Criteria andSeeCountIsNotNull() {
            addCriterion("seeCount is not null");
            return (Criteria) this;
        }

        public Criteria andSeeCountEqualTo(Integer value) {
            addCriterion("seeCount =", value, "seeCount");
            return (Criteria) this;
        }

        public Criteria andSeeCountNotEqualTo(Integer value) {
            addCriterion("seeCount <>", value, "seeCount");
            return (Criteria) this;
        }

        public Criteria andSeeCountGreaterThan(Integer value) {
            addCriterion("seeCount >", value, "seeCount");
            return (Criteria) this;
        }

        public Criteria andSeeCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("seeCount >=", value, "seeCount");
            return (Criteria) this;
        }

        public Criteria andSeeCountLessThan(Integer value) {
            addCriterion("seeCount <", value, "seeCount");
            return (Criteria) this;
        }

        public Criteria andSeeCountLessThanOrEqualTo(Integer value) {
            addCriterion("seeCount <=", value, "seeCount");
            return (Criteria) this;
        }

        public Criteria andSeeCountIn(List<Integer> values) {
            addCriterion("seeCount in", values, "seeCount");
            return (Criteria) this;
        }

        public Criteria andSeeCountNotIn(List<Integer> values) {
            addCriterion("seeCount not in", values, "seeCount");
            return (Criteria) this;
        }

        public Criteria andSeeCountBetween(Integer value1, Integer value2) {
            addCriterion("seeCount between", value1, value2, "seeCount");
            return (Criteria) this;
        }

        public Criteria andSeeCountNotBetween(Integer value1, Integer value2) {
            addCriterion("seeCount not between", value1, value2, "seeCount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table question
     *
     * @mbggenerated do_not_delete_during_merge Tue Mar 27 10:23:40 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table question
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}