package com.internation.info.model;

import java.io.Serializable;
import java.util.Date;

import org.springframework.stereotype.Repository;
@Repository
public class Question implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.title
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.content
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.questioner
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    private Integer questioner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.questionTime
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    private Date questionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.isresolve
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    private Integer isresolve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.professorId
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    private Integer professorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.professorName
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    private String professorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.adoptTheContent
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    private String adoptTheContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.seeCount
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    private Integer seeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.status
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.isdelete
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.title
     *
     * @return the value of question.title
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.title
     *
     * @param title the value for question.title
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.content
     *
     * @return the value of question.content
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.content
     *
     * @param content the value for question.content
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.questioner
     *
     * @return the value of question.questioner
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public Integer getQuestioner() {
        return questioner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.questioner
     *
     * @param questioner the value for question.questioner
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public void setQuestioner(Integer questioner) {
        this.questioner = questioner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.questionTime
     *
     * @return the value of question.questionTime
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public Date getQuestionTime() {
        return questionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.questionTime
     *
     * @param questionTime the value for question.questionTime
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public void setQuestionTime(Date questionTime) {
        this.questionTime = questionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.isresolve
     *
     * @return the value of question.isresolve
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public Integer getIsresolve() {
        return isresolve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.isresolve
     *
     * @param isresolve the value for question.isresolve
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public void setIsresolve(Integer isresolve) {
        this.isresolve = isresolve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.professorId
     *
     * @return the value of question.professorId
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public Integer getProfessorId() {
        return professorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.professorId
     *
     * @param professorId the value for question.professorId
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public void setProfessorId(Integer professorId) {
        this.professorId = professorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.professorName
     *
     * @return the value of question.professorName
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public String getProfessorName() {
        return professorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.professorName
     *
     * @param professorName the value for question.professorName
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public void setProfessorName(String professorName) {
        this.professorName = professorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.adoptTheContent
     *
     * @return the value of question.adoptTheContent
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public String getAdoptTheContent() {
        return adoptTheContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.adoptTheContent
     *
     * @param adoptTheContent the value for question.adoptTheContent
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public void setAdoptTheContent(String adoptTheContent) {
        this.adoptTheContent = adoptTheContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.seeCount
     *
     * @return the value of question.seeCount
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public Integer getSeeCount() {
        return seeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.seeCount
     *
     * @param seeCount the value for question.seeCount
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public void setSeeCount(Integer seeCount) {
        this.seeCount = seeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.status
     *
     * @return the value of question.status
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.status
     *
     * @param status the value for question.status
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.isdelete
     *
     * @return the value of question.isdelete
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.isdelete
     *
     * @param isdelete the value for question.isdelete
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Wed May 02 17:28:48 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", content=").append(content);
        sb.append(", questioner=").append(questioner);
        sb.append(", questionTime=").append(questionTime);
        sb.append(", isresolve=").append(isresolve);
        sb.append(", professorId=").append(professorId);
        sb.append(", professorName=").append(professorName);
        sb.append(", adoptTheContent=").append(adoptTheContent);
        sb.append(", seeCount=").append(seeCount);
        sb.append(", status=").append(status);
        sb.append(", isdelete=").append(isdelete);
        sb.append("]");
        return sb.toString();
    }
}