package com.internation.info.model;

import java.io.Serializable;
import java.util.Date;

import org.springframework.stereotype.Repository;
@Repository
public class Revert implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revert.id
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revert.isRevert
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    private Integer isRevert;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revert.revert
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    private String revert;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revert.uId
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    private Integer uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revert.ArticleId
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revert.reviewFloor
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    private Integer reviewFloor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revert.revertFloor
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    private Integer revertFloor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revert.reviewId
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    private Integer reviewId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revert.revertCreateTime
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    private Date revertCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table revert
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revert.id
     *
     * @return the value of revert.id
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revert.id
     *
     * @param id the value for revert.id
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revert.isRevert
     *
     * @return the value of revert.isRevert
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public Integer getIsRevert() {
        return isRevert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revert.isRevert
     *
     * @param isRevert the value for revert.isRevert
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public void setIsRevert(Integer isRevert) {
        this.isRevert = isRevert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revert.revert
     *
     * @return the value of revert.revert
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public String getRevert() {
        return revert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revert.revert
     *
     * @param revert the value for revert.revert
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public void setRevert(String revert) {
        this.revert = revert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revert.uId
     *
     * @return the value of revert.uId
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revert.uId
     *
     * @param uId the value for revert.uId
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revert.ArticleId
     *
     * @return the value of revert.ArticleId
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revert.ArticleId
     *
     * @param articleId the value for revert.ArticleId
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revert.reviewFloor
     *
     * @return the value of revert.reviewFloor
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public Integer getReviewFloor() {
        return reviewFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revert.reviewFloor
     *
     * @param reviewFloor the value for revert.reviewFloor
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public void setReviewFloor(Integer reviewFloor) {
        this.reviewFloor = reviewFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revert.revertFloor
     *
     * @return the value of revert.revertFloor
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public Integer getRevertFloor() {
        return revertFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revert.revertFloor
     *
     * @param revertFloor the value for revert.revertFloor
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public void setRevertFloor(Integer revertFloor) {
        this.revertFloor = revertFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revert.reviewId
     *
     * @return the value of revert.reviewId
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public Integer getReviewId() {
        return reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revert.reviewId
     *
     * @param reviewId the value for revert.reviewId
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public void setReviewId(Integer reviewId) {
        this.reviewId = reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revert.revertCreateTime
     *
     * @return the value of revert.revertCreateTime
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public Date getRevertCreateTime() {
        return revertCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revert.revertCreateTime
     *
     * @param revertCreateTime the value for revert.revertCreateTime
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public void setRevertCreateTime(Date revertCreateTime) {
        this.revertCreateTime = revertCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revert
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", isRevert=").append(isRevert);
        sb.append(", revert=").append(revert);
        sb.append(", uId=").append(uId);
        sb.append(", articleId=").append(articleId);
        sb.append(", reviewFloor=").append(reviewFloor);
        sb.append(", revertFloor=").append(revertFloor);
        sb.append(", reviewId=").append(reviewId);
        sb.append(", revertCreateTime=").append(revertCreateTime);
        sb.append("]");
        return sb.toString();
    }
}