package com.internation.info.model;

public class user_role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.id
     *
     * @mbggenerated Fri Mar 09 16:16:17 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.user_Id
     *
     * @mbggenerated Fri Mar 09 16:16:17 CST 2018
     */
    private Integer user_Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.role_Id
     *
     * @mbggenerated Fri Mar 09 16:16:17 CST 2018
     */
    private Integer role_Id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.id
     *
     * @return the value of user_role.id
     *
     * @mbggenerated Fri Mar 09 16:16:17 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.id
     *
     * @param id the value for user_role.id
     *
     * @mbggenerated Fri Mar 09 16:16:17 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.user_Id
     *
     * @return the value of user_role.user_Id
     *
     * @mbggenerated Fri Mar 09 16:16:17 CST 2018
     */
    public Integer getUser_Id() {
        return user_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.user_Id
     *
     * @param user_Id the value for user_role.user_Id
     *
     * @mbggenerated Fri Mar 09 16:16:17 CST 2018
     */
    public void setUser_Id(Integer user_Id) {
        this.user_Id = user_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.role_Id
     *
     * @return the value of user_role.role_Id
     *
     * @mbggenerated Fri Mar 09 16:16:17 CST 2018
     */
    public Integer getRole_Id() {
        return role_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.role_Id
     *
     * @param role_Id the value for user_role.role_Id
     *
     * @mbggenerated Fri Mar 09 16:16:17 CST 2018
     */
    public void setRole_Id(Integer role_Id) {
        this.role_Id = role_Id;
    }
}