package com.internation.info.dao;

import com.internation.info.model.Action;
import com.internation.info.model.ActionExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbggenerated Tue Feb 27 13:53:48 CST 2018
     */
    @SelectProvider(type=ActionSqlProvider.class, method="countByExample")
    int countByExample(ActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbggenerated Tue Feb 27 13:53:48 CST 2018
     */
    @DeleteProvider(type=ActionSqlProvider.class, method="deleteByExample")
    int deleteByExample(ActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbggenerated Tue Feb 27 13:53:48 CST 2018
     */
    @Delete({
        "delete from action",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbggenerated Tue Feb 27 13:53:48 CST 2018
     */
    @Insert({
        "insert into action (id, actionId, ",
        "actionCode, actionName)",
        "values (#{id,jdbcType=INTEGER}, #{actionId,jdbcType=INTEGER}, ",
        "#{actionCode,jdbcType=VARCHAR}, #{actionName,jdbcType=VARCHAR})"
    })
    int insert(Action record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbggenerated Tue Feb 27 13:53:48 CST 2018
     */
    @InsertProvider(type=ActionSqlProvider.class, method="insertSelective")
    int insertSelective(Action record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbggenerated Tue Feb 27 13:53:48 CST 2018
     */
    @SelectProvider(type=ActionSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="actionId", property="actionId", jdbcType=JdbcType.INTEGER),
        @Result(column="actionCode", property="actionCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="actionName", property="actionName", jdbcType=JdbcType.VARCHAR)
    })
    List<Action> selectByExample(ActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbggenerated Tue Feb 27 13:53:48 CST 2018
     */
    @Select({
        "select",
        "id, actionId, actionCode, actionName",
        "from action",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="actionId", property="actionId", jdbcType=JdbcType.INTEGER),
        @Result(column="actionCode", property="actionCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="actionName", property="actionName", jdbcType=JdbcType.VARCHAR)
    })
    Action selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbggenerated Tue Feb 27 13:53:48 CST 2018
     */
    @UpdateProvider(type=ActionSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Action record, @Param("example") ActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbggenerated Tue Feb 27 13:53:48 CST 2018
     */
    @UpdateProvider(type=ActionSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Action record, @Param("example") ActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbggenerated Tue Feb 27 13:53:48 CST 2018
     */
    @UpdateProvider(type=ActionSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Action record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbggenerated Tue Feb 27 13:53:48 CST 2018
     */
    @Update({
        "update action",
        "set actionId = #{actionId,jdbcType=INTEGER},",
          "actionCode = #{actionCode,jdbcType=VARCHAR},",
          "actionName = #{actionName,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Action record);
}