package com.internation.info.dao;

import com.internation.info.model.Article;
import com.internation.info.model.ArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @SelectProvider(type=ArticleSqlProvider.class, method="countByExample")
    int countByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @DeleteProvider(type=ArticleSqlProvider.class, method="deleteByExample")
    int deleteByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @Delete({
        "delete from article",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @Insert({
        "insert into article (id, title, ",
        "original, content, ",
        "uid, blog_type, ",
        "ispublish, isprivate, ",
        "createTime, seecount, ",
        "identifyingCode)",
        "values (#{id,jdbcType=INTEGER}, #{title,jdbcType=VARCHAR}, ",
        "#{original,jdbcType=INTEGER}, #{content,jdbcType=VARCHAR}, ",
        "#{uid,jdbcType=INTEGER}, #{blog_type,jdbcType=VARCHAR}, ",
        "#{ispublish,jdbcType=INTEGER}, #{isprivate,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{seecount,jdbcType=INTEGER}, ",
        "#{identifyingCode,jdbcType=VARCHAR})"
    })
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @InsertProvider(type=ArticleSqlProvider.class, method="insertSelective")
    int insertSelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @SelectProvider(type=ArticleSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="original", property="original", jdbcType=JdbcType.INTEGER),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="uid", property="uid", jdbcType=JdbcType.INTEGER),
        @Result(column="blog_type", property="blog_type", jdbcType=JdbcType.VARCHAR),
        @Result(column="ispublish", property="ispublish", jdbcType=JdbcType.INTEGER),
        @Result(column="isprivate", property="isprivate", jdbcType=JdbcType.INTEGER),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="seecount", property="seecount", jdbcType=JdbcType.INTEGER),
        @Result(column="identifyingCode", property="identifyingCode", jdbcType=JdbcType.VARCHAR)
    })
    List<Article> selectByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @Select({
        "select",
        "id, title, original, content, uid, blog_type, ispublish, isprivate, createTime, ",
        "seecount, identifyingCode",
        "from article",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="original", property="original", jdbcType=JdbcType.INTEGER),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="uid", property="uid", jdbcType=JdbcType.INTEGER),
        @Result(column="blog_type", property="blog_type", jdbcType=JdbcType.VARCHAR),
        @Result(column="ispublish", property="ispublish", jdbcType=JdbcType.INTEGER),
        @Result(column="isprivate", property="isprivate", jdbcType=JdbcType.INTEGER),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="seecount", property="seecount", jdbcType=JdbcType.INTEGER),
        @Result(column="identifyingCode", property="identifyingCode", jdbcType=JdbcType.VARCHAR)
    })
    Article selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @UpdateProvider(type=ArticleSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @UpdateProvider(type=ArticleSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @UpdateProvider(type=ArticleSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @Update({
        "update article",
        "set title = #{title,jdbcType=VARCHAR},",
          "original = #{original,jdbcType=INTEGER},",
          "content = #{content,jdbcType=VARCHAR},",
          "uid = #{uid,jdbcType=INTEGER},",
          "blog_type = #{blog_type,jdbcType=VARCHAR},",
          "ispublish = #{ispublish,jdbcType=INTEGER},",
          "isprivate = #{isprivate,jdbcType=INTEGER},",
          "createTime = #{createTime,jdbcType=TIMESTAMP},",
          "seecount = #{seecount,jdbcType=INTEGER},",
          "identifyingCode = #{identifyingCode,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Article record);
}