package com.internation.info.dao;


import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.internation.info.model.BasicMessageWall;
import com.internation.info.model.BasicMessageWallExample;

public interface BasicMessageWallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicmessagewall
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    @SelectProvider(type=BasicMessageWallSqlProvider.class, method="countByExample")
    int countByExample(BasicMessageWallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicmessagewall
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    @DeleteProvider(type=BasicMessageWallSqlProvider.class, method="deleteByExample")
    int deleteByExample(BasicMessageWallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicmessagewall
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    @Delete({
        "delete from basicmessagewall",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicmessagewall
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    @Insert({
        "insert into basicmessagewall (id, userId, ",
        "userName, content, ",
        "createTime, updateTime)",
        "values (#{id,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{userName,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(BasicMessageWall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicmessagewall
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    @InsertProvider(type=BasicMessageWallSqlProvider.class, method="insertSelective")
    int insertSelective(BasicMessageWall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicmessagewall
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    @SelectProvider(type=BasicMessageWallSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="userId", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="userName", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updateTime", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<BasicMessageWall> selectByExample(BasicMessageWallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicmessagewall
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    @Select({
        "select",
        "id, userId, userName, content, createTime, updateTime",
        "from basicmessagewall",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="userId", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="userName", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updateTime", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    BasicMessageWall selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicmessagewall
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    @UpdateProvider(type=BasicMessageWallSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BasicMessageWall record, @Param("example") BasicMessageWallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicmessagewall
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    @UpdateProvider(type=BasicMessageWallSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BasicMessageWall record, @Param("example") BasicMessageWallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicmessagewall
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    @UpdateProvider(type=BasicMessageWallSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BasicMessageWall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicmessagewall
     *
     * @mbggenerated Wed Apr 18 09:16:18 CST 2018
     */
    @Update({
        "update basicmessagewall",
        "set userId = #{userId,jdbcType=INTEGER},",
          "userName = #{userName,jdbcType=VARCHAR},",
          "content = #{content,jdbcType=VARCHAR},",
          "createTime = #{createTime,jdbcType=TIMESTAMP},",
          "updateTime = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BasicMessageWall record);
}