package com.internation.info.dao;

import com.internation.info.model.FileDownload;
import com.internation.info.model.FileDownloadExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface FileDownloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedownload
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    @SelectProvider(type=FileDownloadSqlProvider.class, method="countByExample")
    int countByExample(FileDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedownload
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    @DeleteProvider(type=FileDownloadSqlProvider.class, method="deleteByExample")
    int deleteByExample(FileDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedownload
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    @Delete({
        "delete from filedownload",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedownload
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    @Insert({
        "insert into filedownload (id, fileId, ",
        "fileName, uId, downLoadTime)",
        "values (#{id,jdbcType=INTEGER}, #{fileId,jdbcType=INTEGER}, ",
        "#{fileName,jdbcType=VARCHAR}, #{uId,jdbcType=INTEGER}, #{downLoadTime,jdbcType=TIMESTAMP})"
    })
    int insert(FileDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedownload
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    @InsertProvider(type=FileDownloadSqlProvider.class, method="insertSelective")
    int insertSelective(FileDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedownload
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    @SelectProvider(type=FileDownloadSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="fileId", property="fileId", jdbcType=JdbcType.INTEGER),
        @Result(column="fileName", property="fileName", jdbcType=JdbcType.VARCHAR),
        @Result(column="uId", property="uId", jdbcType=JdbcType.INTEGER),
        @Result(column="downLoadTime", property="downLoadTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<FileDownload> selectByExample(FileDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedownload
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    @Select({
        "select",
        "id, fileId, fileName, uId, downLoadTime",
        "from filedownload",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="fileId", property="fileId", jdbcType=JdbcType.INTEGER),
        @Result(column="fileName", property="fileName", jdbcType=JdbcType.VARCHAR),
        @Result(column="uId", property="uId", jdbcType=JdbcType.INTEGER),
        @Result(column="downLoadTime", property="downLoadTime", jdbcType=JdbcType.TIMESTAMP)
    })
    FileDownload selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedownload
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    @UpdateProvider(type=FileDownloadSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") FileDownload record, @Param("example") FileDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedownload
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    @UpdateProvider(type=FileDownloadSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") FileDownload record, @Param("example") FileDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedownload
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    @UpdateProvider(type=FileDownloadSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(FileDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedownload
     *
     * @mbggenerated Sat Apr 14 19:23:48 CST 2018
     */
    @Update({
        "update filedownload",
        "set fileId = #{fileId,jdbcType=INTEGER},",
          "fileName = #{fileName,jdbcType=VARCHAR},",
          "uId = #{uId,jdbcType=INTEGER},",
          "downLoadTime = #{downLoadTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(FileDownload record);
}