package com.internation.info.dao;

import com.internation.info.model.GroupMember;
import com.internation.info.model.GroupMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface GroupMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmember
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    @SelectProvider(type=GroupMemberSqlProvider.class, method="countByExample")
    int countByExample(GroupMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmember
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    @DeleteProvider(type=GroupMemberSqlProvider.class, method="deleteByExample")
    int deleteByExample(GroupMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmember
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    @Delete({
        "delete from groupmember",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmember
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    @Insert({
        "insert into groupmember (id, groupId, ",
        "member, createdTime, ",
        "status, nickName, ",
        "avatar, sign)",
        "values (#{id,jdbcType=INTEGER}, #{groupId,jdbcType=INTEGER}, ",
        "#{member,jdbcType=VARCHAR}, #{createdTime,jdbcType=TIMESTAMP}, ",
        "#{status,jdbcType=VARCHAR}, #{nickName,jdbcType=VARCHAR}, ",
        "#{avatar,jdbcType=VARCHAR}, #{sign,jdbcType=VARCHAR})"
    })
    int insert(GroupMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmember
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    @InsertProvider(type=GroupMemberSqlProvider.class, method="insertSelective")
    int insertSelective(GroupMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmember
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    @SelectProvider(type=GroupMemberSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="groupId", property="groupId", jdbcType=JdbcType.INTEGER),
        @Result(column="member", property="member", jdbcType=JdbcType.VARCHAR),
        @Result(column="createdTime", property="createdTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="nickName", property="nickName", jdbcType=JdbcType.VARCHAR),
        @Result(column="avatar", property="avatar", jdbcType=JdbcType.VARCHAR),
        @Result(column="sign", property="sign", jdbcType=JdbcType.VARCHAR)
    })
    List<GroupMember> selectByExample(GroupMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmember
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    @Select({
        "select",
        "id, groupId, member, createdTime, status, nickName, avatar, sign",
        "from groupmember",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="groupId", property="groupId", jdbcType=JdbcType.INTEGER),
        @Result(column="member", property="member", jdbcType=JdbcType.VARCHAR),
        @Result(column="createdTime", property="createdTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="nickName", property="nickName", jdbcType=JdbcType.VARCHAR),
        @Result(column="avatar", property="avatar", jdbcType=JdbcType.VARCHAR),
        @Result(column="sign", property="sign", jdbcType=JdbcType.VARCHAR)
    })
    GroupMember selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmember
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    @UpdateProvider(type=GroupMemberSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") GroupMember record, @Param("example") GroupMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmember
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    @UpdateProvider(type=GroupMemberSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") GroupMember record, @Param("example") GroupMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmember
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    @UpdateProvider(type=GroupMemberSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GroupMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmember
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    @Update({
        "update groupmember",
        "set groupId = #{groupId,jdbcType=INTEGER},",
          "member = #{member,jdbcType=VARCHAR},",
          "createdTime = #{createdTime,jdbcType=TIMESTAMP},",
          "status = #{status,jdbcType=VARCHAR},",
          "nickName = #{nickName,jdbcType=VARCHAR},",
          "avatar = #{avatar,jdbcType=VARCHAR},",
          "sign = #{sign,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(GroupMember record);
}