package com.internation.info.dao;

import com.internation.info.model.GroupMember;
import com.internation.info.model.GroupMemberExample.Criteria;
import com.internation.info.model.GroupMemberExample.Criterion;
import com.internation.info.model.GroupMemberExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class GroupMemberSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmember
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    public String countByExample(GroupMemberExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("groupmember");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmember
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    public String deleteByExample(GroupMemberExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("groupmember");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmember
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    public String insertSelective(GroupMember record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("groupmember");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getGroupId() != null) {
            sql.VALUES("groupId", "#{groupId,jdbcType=INTEGER}");
        }
        
        if (record.getMember() != null) {
            sql.VALUES("member", "#{member,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedTime() != null) {
            sql.VALUES("createdTime", "#{createdTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getStatus() != null) {
            sql.VALUES("status", "#{status,jdbcType=VARCHAR}");
        }
        
        if (record.getNickName() != null) {
            sql.VALUES("nickName", "#{nickName,jdbcType=VARCHAR}");
        }
        
        if (record.getAvatar() != null) {
            sql.VALUES("avatar", "#{avatar,jdbcType=VARCHAR}");
        }
        
        if (record.getSign() != null) {
            sql.VALUES("sign", "#{sign,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmember
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    public String selectByExample(GroupMemberExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("groupId");
        sql.SELECT("member");
        sql.SELECT("createdTime");
        sql.SELECT("status");
        sql.SELECT("nickName");
        sql.SELECT("avatar");
        sql.SELECT("sign");
        sql.FROM("groupmember");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmember
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        GroupMember record = (GroupMember) parameter.get("record");
        GroupMemberExample example = (GroupMemberExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("groupmember");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getGroupId() != null) {
            sql.SET("groupId = #{record.groupId,jdbcType=INTEGER}");
        }
        
        if (record.getMember() != null) {
            sql.SET("member = #{record.member,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedTime() != null) {
            sql.SET("createdTime = #{record.createdTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{record.status,jdbcType=VARCHAR}");
        }
        
        if (record.getNickName() != null) {
            sql.SET("nickName = #{record.nickName,jdbcType=VARCHAR}");
        }
        
        if (record.getAvatar() != null) {
            sql.SET("avatar = #{record.avatar,jdbcType=VARCHAR}");
        }
        
        if (record.getSign() != null) {
            sql.SET("sign = #{record.sign,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmember
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("groupmember");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("groupId = #{record.groupId,jdbcType=INTEGER}");
        sql.SET("member = #{record.member,jdbcType=VARCHAR}");
        sql.SET("createdTime = #{record.createdTime,jdbcType=TIMESTAMP}");
        sql.SET("status = #{record.status,jdbcType=VARCHAR}");
        sql.SET("nickName = #{record.nickName,jdbcType=VARCHAR}");
        sql.SET("avatar = #{record.avatar,jdbcType=VARCHAR}");
        sql.SET("sign = #{record.sign,jdbcType=VARCHAR}");
        
        GroupMemberExample example = (GroupMemberExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmember
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    public String updateByPrimaryKeySelective(GroupMember record) {
        SQL sql = new SQL();
        sql.UPDATE("groupmember");
        
        if (record.getGroupId() != null) {
            sql.SET("groupId = #{groupId,jdbcType=INTEGER}");
        }
        
        if (record.getMember() != null) {
            sql.SET("member = #{member,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedTime() != null) {
            sql.SET("createdTime = #{createdTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{status,jdbcType=VARCHAR}");
        }
        
        if (record.getNickName() != null) {
            sql.SET("nickName = #{nickName,jdbcType=VARCHAR}");
        }
        
        if (record.getAvatar() != null) {
            sql.SET("avatar = #{avatar,jdbcType=VARCHAR}");
        }
        
        if (record.getSign() != null) {
            sql.SET("sign = #{sign,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmember
     *
     * @mbggenerated Sat Apr 28 22:20:51 CST 2018
     */
    protected void applyWhere(SQL sql, GroupMemberExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}