package com.internation.info.dao;

import com.internation.info.model.Integration;
import com.internation.info.model.IntegrationExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface IntegrationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integration
     *
     * @mbggenerated Tue Feb 27 13:53:48 CST 2018
     */
    @SelectProvider(type=IntegrationSqlProvider.class, method="countByExample")
    int countByExample(IntegrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integration
     *
     * @mbggenerated Tue Feb 27 13:53:48 CST 2018
     */
    @DeleteProvider(type=IntegrationSqlProvider.class, method="deleteByExample")
    int deleteByExample(IntegrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integration
     *
     * @mbggenerated Tue Feb 27 13:53:48 CST 2018
     */
    @Delete({
        "delete from integration",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integration
     *
     * @mbggenerated Tue Feb 27 13:53:48 CST 2018
     */
    @Insert({
        "insert into integration (id, integration_number, ",
        "userId)",
        "values (#{id,jdbcType=INTEGER}, #{integration_number,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=INTEGER})"
    })
    int insert(Integration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integration
     *
     * @mbggenerated Tue Feb 27 13:53:48 CST 2018
     */
    @InsertProvider(type=IntegrationSqlProvider.class, method="insertSelective")
    int insertSelective(Integration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integration
     *
     * @mbggenerated Tue Feb 27 13:53:48 CST 2018
     */
    @SelectProvider(type=IntegrationSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="integration_number", property="integration_number", jdbcType=JdbcType.INTEGER),
        @Result(column="userId", property="userId", jdbcType=JdbcType.INTEGER)
    })
    List<Integration> selectByExample(IntegrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integration
     *
     * @mbggenerated Tue Feb 27 13:53:48 CST 2018
     */
    @Select({
        "select",
        "id, integration_number, userId",
        "from integration",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="integration_number", property="integration_number", jdbcType=JdbcType.INTEGER),
        @Result(column="userId", property="userId", jdbcType=JdbcType.INTEGER)
    })
    Integration selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integration
     *
     * @mbggenerated Tue Feb 27 13:53:48 CST 2018
     */
    @UpdateProvider(type=IntegrationSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Integration record, @Param("example") IntegrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integration
     *
     * @mbggenerated Tue Feb 27 13:53:48 CST 2018
     */
    @UpdateProvider(type=IntegrationSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Integration record, @Param("example") IntegrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integration
     *
     * @mbggenerated Tue Feb 27 13:53:48 CST 2018
     */
    @UpdateProvider(type=IntegrationSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Integration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integration
     *
     * @mbggenerated Tue Feb 27 13:53:48 CST 2018
     */
    @Update({
        "update integration",
        "set integration_number = #{integration_number,jdbcType=INTEGER},",
          "userId = #{userId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Integration record);
}