package com.internation.info.dao;

import com.internation.info.model.MyCollection;
import com.internation.info.model.MyCollectionExample.Criteria;
import com.internation.info.model.MyCollectionExample.Criterion;
import com.internation.info.model.MyCollectionExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class MyCollectionSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated Tue Apr 10 15:11:12 CST 2018
     */
    public String countByExample(MyCollectionExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("my_collection");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated Tue Apr 10 15:11:12 CST 2018
     */
    public String deleteByExample(MyCollectionExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("my_collection");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated Tue Apr 10 15:11:12 CST 2018
     */
    public String insertSelective(MyCollection record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("my_collection");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getuId() != null) {
            sql.VALUES("uId", "#{uId,jdbcType=INTEGER}");
        }
        
        if (record.getIsUser() != null) {
            sql.VALUES("isUser", "#{isUser,jdbcType=INTEGER}");
        }
        
        if (record.getMyAttentionUserId() != null) {
            sql.VALUES("myAttentionUserId", "#{myAttentionUserId,jdbcType=INTEGER}");
        }
        
        if (record.getIsQuestion() != null) {
            sql.VALUES("isQuestion", "#{isQuestion,jdbcType=INTEGER}");
        }
        
        if (record.getMyCollectionOnArticleId() != null) {
            sql.VALUES("myCollectionOnArticleId", "#{myCollectionOnArticleId,jdbcType=INTEGER}");
        }
        
        if (record.getMyCollectionOnQuestionId() != null) {
            sql.VALUES("myCollectionOnQuestionId", "#{myCollectionOnQuestionId,jdbcType=INTEGER}");
        }
        
        if (record.getIsArticle() != null) {
            sql.VALUES("isArticle", "#{isArticle,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated Tue Apr 10 15:11:12 CST 2018
     */
    public String selectByExample(MyCollectionExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("uId");
        sql.SELECT("isUser");
        sql.SELECT("myAttentionUserId");
        sql.SELECT("isQuestion");
        sql.SELECT("myCollectionOnArticleId");
        sql.SELECT("myCollectionOnQuestionId");
        sql.SELECT("isArticle");
        sql.FROM("my_collection");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated Tue Apr 10 15:11:12 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        MyCollection record = (MyCollection) parameter.get("record");
        MyCollectionExample example = (MyCollectionExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("my_collection");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getuId() != null) {
            sql.SET("uId = #{record.uId,jdbcType=INTEGER}");
        }
        
        if (record.getIsUser() != null) {
            sql.SET("isUser = #{record.isUser,jdbcType=INTEGER}");
        }
        
        if (record.getMyAttentionUserId() != null) {
            sql.SET("myAttentionUserId = #{record.myAttentionUserId,jdbcType=INTEGER}");
        }
        
        if (record.getIsQuestion() != null) {
            sql.SET("isQuestion = #{record.isQuestion,jdbcType=INTEGER}");
        }
        
        if (record.getMyCollectionOnArticleId() != null) {
            sql.SET("myCollectionOnArticleId = #{record.myCollectionOnArticleId,jdbcType=INTEGER}");
        }
        
        if (record.getMyCollectionOnQuestionId() != null) {
            sql.SET("myCollectionOnQuestionId = #{record.myCollectionOnQuestionId,jdbcType=INTEGER}");
        }
        
        if (record.getIsArticle() != null) {
            sql.SET("isArticle = #{record.isArticle,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated Tue Apr 10 15:11:12 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("my_collection");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("uId = #{record.uId,jdbcType=INTEGER}");
        sql.SET("isUser = #{record.isUser,jdbcType=INTEGER}");
        sql.SET("myAttentionUserId = #{record.myAttentionUserId,jdbcType=INTEGER}");
        sql.SET("isQuestion = #{record.isQuestion,jdbcType=INTEGER}");
        sql.SET("myCollectionOnArticleId = #{record.myCollectionOnArticleId,jdbcType=INTEGER}");
        sql.SET("myCollectionOnQuestionId = #{record.myCollectionOnQuestionId,jdbcType=INTEGER}");
        sql.SET("isArticle = #{record.isArticle,jdbcType=INTEGER}");
        
        MyCollectionExample example = (MyCollectionExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated Tue Apr 10 15:11:12 CST 2018
     */
    public String updateByPrimaryKeySelective(MyCollection record) {
        SQL sql = new SQL();
        sql.UPDATE("my_collection");
        
        if (record.getuId() != null) {
            sql.SET("uId = #{uId,jdbcType=INTEGER}");
        }
        
        if (record.getIsUser() != null) {
            sql.SET("isUser = #{isUser,jdbcType=INTEGER}");
        }
        
        if (record.getMyAttentionUserId() != null) {
            sql.SET("myAttentionUserId = #{myAttentionUserId,jdbcType=INTEGER}");
        }
        
        if (record.getIsQuestion() != null) {
            sql.SET("isQuestion = #{isQuestion,jdbcType=INTEGER}");
        }
        
        if (record.getMyCollectionOnArticleId() != null) {
            sql.SET("myCollectionOnArticleId = #{myCollectionOnArticleId,jdbcType=INTEGER}");
        }
        
        if (record.getMyCollectionOnQuestionId() != null) {
            sql.SET("myCollectionOnQuestionId = #{myCollectionOnQuestionId,jdbcType=INTEGER}");
        }
        
        if (record.getIsArticle() != null) {
            sql.SET("isArticle = #{isArticle,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_collection
     *
     * @mbggenerated Tue Apr 10 15:11:12 CST 2018
     */
    protected void applyWhere(SQL sql, MyCollectionExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}