package com.internation.info.dao;

import com.internation.info.model.Revert;
import com.internation.info.model.RevertExample.Criteria;
import com.internation.info.model.RevertExample.Criterion;
import com.internation.info.model.RevertExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class RevertSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revert
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public String countByExample(RevertExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("revert");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revert
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public String deleteByExample(RevertExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("revert");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revert
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public String insertSelective(Revert record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("revert");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getIsRevert() != null) {
            sql.VALUES("isRevert", "#{isRevert,jdbcType=INTEGER}");
        }
        
        if (record.getRevert() != null) {
            sql.VALUES("revert", "#{revert,jdbcType=VARCHAR}");
        }
        
        if (record.getuId() != null) {
            sql.VALUES("uId", "#{uId,jdbcType=INTEGER}");
        }
        
        if (record.getArticleId() != null) {
            sql.VALUES("ArticleId", "#{articleId,jdbcType=INTEGER}");
        }
        
        if (record.getReviewFloor() != null) {
            sql.VALUES("reviewFloor", "#{reviewFloor,jdbcType=INTEGER}");
        }
        
        if (record.getRevertFloor() != null) {
            sql.VALUES("revertFloor", "#{revertFloor,jdbcType=INTEGER}");
        }
        
        if (record.getReviewId() != null) {
            sql.VALUES("reviewId", "#{reviewId,jdbcType=INTEGER}");
        }
        
        if (record.getRevertCreateTime() != null) {
            sql.VALUES("revertCreateTime", "#{revertCreateTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revert
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public String selectByExample(RevertExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("isRevert");
        sql.SELECT("revert");
        sql.SELECT("uId");
        sql.SELECT("ArticleId");
        sql.SELECT("reviewFloor");
        sql.SELECT("revertFloor");
        sql.SELECT("reviewId");
        sql.SELECT("revertCreateTime");
        sql.FROM("revert");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revert
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Revert record = (Revert) parameter.get("record");
        RevertExample example = (RevertExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("revert");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getIsRevert() != null) {
            sql.SET("isRevert = #{record.isRevert,jdbcType=INTEGER}");
        }
        
        if (record.getRevert() != null) {
            sql.SET("revert = #{record.revert,jdbcType=VARCHAR}");
        }
        
        if (record.getuId() != null) {
            sql.SET("uId = #{record.uId,jdbcType=INTEGER}");
        }
        
        if (record.getArticleId() != null) {
            sql.SET("ArticleId = #{record.articleId,jdbcType=INTEGER}");
        }
        
        if (record.getReviewFloor() != null) {
            sql.SET("reviewFloor = #{record.reviewFloor,jdbcType=INTEGER}");
        }
        
        if (record.getRevertFloor() != null) {
            sql.SET("revertFloor = #{record.revertFloor,jdbcType=INTEGER}");
        }
        
        if (record.getReviewId() != null) {
            sql.SET("reviewId = #{record.reviewId,jdbcType=INTEGER}");
        }
        
        if (record.getRevertCreateTime() != null) {
            sql.SET("revertCreateTime = #{record.revertCreateTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revert
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("revert");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("isRevert = #{record.isRevert,jdbcType=INTEGER}");
        sql.SET("revert = #{record.revert,jdbcType=VARCHAR}");
        sql.SET("uId = #{record.uId,jdbcType=INTEGER}");
        sql.SET("ArticleId = #{record.articleId,jdbcType=INTEGER}");
        sql.SET("reviewFloor = #{record.reviewFloor,jdbcType=INTEGER}");
        sql.SET("revertFloor = #{record.revertFloor,jdbcType=INTEGER}");
        sql.SET("reviewId = #{record.reviewId,jdbcType=INTEGER}");
        sql.SET("revertCreateTime = #{record.revertCreateTime,jdbcType=TIMESTAMP}");
        
        RevertExample example = (RevertExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revert
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    public String updateByPrimaryKeySelective(Revert record) {
        SQL sql = new SQL();
        sql.UPDATE("revert");
        
        if (record.getIsRevert() != null) {
            sql.SET("isRevert = #{isRevert,jdbcType=INTEGER}");
        }
        
        if (record.getRevert() != null) {
            sql.SET("revert = #{revert,jdbcType=VARCHAR}");
        }
        
        if (record.getuId() != null) {
            sql.SET("uId = #{uId,jdbcType=INTEGER}");
        }
        
        if (record.getArticleId() != null) {
            sql.SET("ArticleId = #{articleId,jdbcType=INTEGER}");
        }
        
        if (record.getReviewFloor() != null) {
            sql.SET("reviewFloor = #{reviewFloor,jdbcType=INTEGER}");
        }
        
        if (record.getRevertFloor() != null) {
            sql.SET("revertFloor = #{revertFloor,jdbcType=INTEGER}");
        }
        
        if (record.getReviewId() != null) {
            sql.SET("reviewId = #{reviewId,jdbcType=INTEGER}");
        }
        
        if (record.getRevertCreateTime() != null) {
            sql.SET("revertCreateTime = #{revertCreateTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revert
     *
     * @mbggenerated Mon Apr 23 15:33:04 CST 2018
     */
    protected void applyWhere(SQL sql, RevertExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}