package com.internation.info.dao;

import com.internation.info.model.Review;
import com.internation.info.model.ReviewExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ReviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @SelectProvider(type=ReviewSqlProvider.class, method="countByExample")
    int countByExample(ReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @DeleteProvider(type=ReviewSqlProvider.class, method="deleteByExample")
    int deleteByExample(ReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @Delete({
        "delete from review",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @Insert({
        "insert into review (id, article_title, ",
        "authorId, observer_id, ",
        "article_id, message, ",
        "revert, createTime, ",
        "floor_number, like_number, ",
        "unlike_number, seecount)",
        "values (#{id,jdbcType=INTEGER}, #{article_title,jdbcType=VARCHAR}, ",
        "#{authorId,jdbcType=INTEGER}, #{observer_id,jdbcType=INTEGER}, ",
        "#{article_id,jdbcType=INTEGER}, #{message,jdbcType=VARCHAR}, ",
        "#{revert,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{floor_number,jdbcType=INTEGER}, #{like_number,jdbcType=INTEGER}, ",
        "#{unlike_number,jdbcType=INTEGER}, #{seecount,jdbcType=INTEGER})"
    })
    int insert(Review record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @InsertProvider(type=ReviewSqlProvider.class, method="insertSelective")
    int insertSelective(Review record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @SelectProvider(type=ReviewSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="article_title", property="article_title", jdbcType=JdbcType.VARCHAR),
        @Result(column="authorId", property="authorId", jdbcType=JdbcType.INTEGER),
        @Result(column="observer_id", property="observer_id", jdbcType=JdbcType.INTEGER),
        @Result(column="article_id", property="article_id", jdbcType=JdbcType.INTEGER),
        @Result(column="message", property="message", jdbcType=JdbcType.VARCHAR),
        @Result(column="revert", property="revert", jdbcType=JdbcType.VARCHAR),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="floor_number", property="floor_number", jdbcType=JdbcType.INTEGER),
        @Result(column="like_number", property="like_number", jdbcType=JdbcType.INTEGER),
        @Result(column="unlike_number", property="unlike_number", jdbcType=JdbcType.INTEGER),
        @Result(column="seecount", property="seecount", jdbcType=JdbcType.INTEGER)
    })
    List<Review> selectByExample(ReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @Select({
        "select",
        "id, article_title, authorId, observer_id, article_id, message, revert, createTime, ",
        "floor_number, like_number, unlike_number, seecount",
        "from review",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="article_title", property="article_title", jdbcType=JdbcType.VARCHAR),
        @Result(column="authorId", property="authorId", jdbcType=JdbcType.INTEGER),
        @Result(column="observer_id", property="observer_id", jdbcType=JdbcType.INTEGER),
        @Result(column="article_id", property="article_id", jdbcType=JdbcType.INTEGER),
        @Result(column="message", property="message", jdbcType=JdbcType.VARCHAR),
        @Result(column="revert", property="revert", jdbcType=JdbcType.VARCHAR),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="floor_number", property="floor_number", jdbcType=JdbcType.INTEGER),
        @Result(column="like_number", property="like_number", jdbcType=JdbcType.INTEGER),
        @Result(column="unlike_number", property="unlike_number", jdbcType=JdbcType.INTEGER),
        @Result(column="seecount", property="seecount", jdbcType=JdbcType.INTEGER)
    })
    Review selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @UpdateProvider(type=ReviewSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Review record, @Param("example") ReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @UpdateProvider(type=ReviewSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Review record, @Param("example") ReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @UpdateProvider(type=ReviewSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Review record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @Update({
        "update review",
        "set article_title = #{article_title,jdbcType=VARCHAR},",
          "authorId = #{authorId,jdbcType=INTEGER},",
          "observer_id = #{observer_id,jdbcType=INTEGER},",
          "article_id = #{article_id,jdbcType=INTEGER},",
          "message = #{message,jdbcType=VARCHAR},",
          "revert = #{revert,jdbcType=VARCHAR},",
          "createTime = #{createTime,jdbcType=TIMESTAMP},",
          "floor_number = #{floor_number,jdbcType=INTEGER},",
          "like_number = #{like_number,jdbcType=INTEGER},",
          "unlike_number = #{unlike_number,jdbcType=INTEGER},",
          "seecount = #{seecount,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Review record);
}