package com.internation.info.dao;

import com.internation.info.model.User_Role;
import com.internation.info.model.User_RoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface User_RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @SelectProvider(type=User_RoleSqlProvider.class, method="countByExample")
    int countByExample(User_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @DeleteProvider(type=User_RoleSqlProvider.class, method="deleteByExample")
    int deleteByExample(User_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @Delete({
        "delete from user_role",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @Insert({
        "insert into user_role (id, user_Id, ",
        "role_Id)",
        "values (#{id,jdbcType=INTEGER}, #{user_Id,jdbcType=INTEGER}, ",
        "#{role_Id,jdbcType=INTEGER})"
    })
    int insert(User_Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @InsertProvider(type=User_RoleSqlProvider.class, method="insertSelective")
    int insertSelective(User_Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @SelectProvider(type=User_RoleSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_Id", property="user_Id", jdbcType=JdbcType.INTEGER),
        @Result(column="role_Id", property="role_Id", jdbcType=JdbcType.INTEGER)
    })
    List<User_Role> selectByExample(User_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @Select({
        "select",
        "id, user_Id, role_Id",
        "from user_role",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_Id", property="user_Id", jdbcType=JdbcType.INTEGER),
        @Result(column="role_Id", property="role_Id", jdbcType=JdbcType.INTEGER)
    })
    User_Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @UpdateProvider(type=User_RoleSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") User_Role record, @Param("example") User_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @UpdateProvider(type=User_RoleSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") User_Role record, @Param("example") User_RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @UpdateProvider(type=User_RoleSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(User_Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Mar 27 10:23:40 CST 2018
     */
    @Update({
        "update user_role",
        "set user_Id = #{user_Id,jdbcType=INTEGER},",
          "role_Id = #{role_Id,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(User_Role record);
}