package com.internation.info.dao;

import com.internation.info.model.user_role;
import com.internation.info.model.user_roleExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface user_roleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Fri Mar 09 16:16:17 CST 2018
     */
    @SelectProvider(type=user_roleSqlProvider.class, method="countByExample")
    int countByExample(user_roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Fri Mar 09 16:16:17 CST 2018
     */
    @DeleteProvider(type=user_roleSqlProvider.class, method="deleteByExample")
    int deleteByExample(user_roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Fri Mar 09 16:16:17 CST 2018
     */
    @Delete({
        "delete from user_role",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Fri Mar 09 16:16:17 CST 2018
     */
    @Insert({
        "insert into user_role (id, user_Id, ",
        "role_Id)",
        "values (#{id,jdbcType=INTEGER}, #{user_Id,jdbcType=INTEGER}, ",
        "#{role_Id,jdbcType=INTEGER})"
    })
    int insert(user_role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Fri Mar 09 16:16:17 CST 2018
     */
    @InsertProvider(type=user_roleSqlProvider.class, method="insertSelective")
    int insertSelective(user_role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Fri Mar 09 16:16:17 CST 2018
     */
    @SelectProvider(type=user_roleSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_Id", property="user_Id", jdbcType=JdbcType.INTEGER),
        @Result(column="role_Id", property="role_Id", jdbcType=JdbcType.INTEGER)
    })
    List<user_role> selectByExample(user_roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Fri Mar 09 16:16:17 CST 2018
     */
    @Select({
        "select",
        "id, user_Id, role_Id",
        "from user_role",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_Id", property="user_Id", jdbcType=JdbcType.INTEGER),
        @Result(column="role_Id", property="role_Id", jdbcType=JdbcType.INTEGER)
    })
    user_role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Fri Mar 09 16:16:17 CST 2018
     */
    @UpdateProvider(type=user_roleSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") user_role record, @Param("example") user_roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Fri Mar 09 16:16:17 CST 2018
     */
    @UpdateProvider(type=user_roleSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") user_role record, @Param("example") user_roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Fri Mar 09 16:16:17 CST 2018
     */
    @UpdateProvider(type=user_roleSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(user_role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Fri Mar 09 16:16:17 CST 2018
     */
    @Update({
        "update user_role",
        "set user_Id = #{user_Id,jdbcType=INTEGER},",
          "role_Id = #{role_Id,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(user_role record);
}